server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/onezo/sample-config
        default-label: master
        basedir: ./repo
  output.ansi.enabled: always