server:
  port: 9091

spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

url:
  apiGateway: http://localhost:8000
